services:
  # client-web:
  #     - api
  api:
    container_name: go-api
    volumes:
      - ./backend:/app:rw
    build:
      context: ./backend/
      dockerfile: backend.Dockerfile
    ports:
      - "8001:8000"
    tty: true
    stdin_open: true
    env_file:
      - ./backend/.env.development
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    depends_on:
      - db
  db:
    container_name: postgres-db
    image: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_DB=db
      - POSTGRES_PASSWORD=admin
  adminer:
    container_name: amdiner
    image: adminer
    ports:
      - "8081:8080"
  metrics:
    image: prom/prometheus
    volumes:
      - "./backend/prometheus.yml:/etc/prometheus/prometheus.yml"
    ports:
      - 9090:9090
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
  redis:
    image: redis:7.4-alpine
    container_name: go-redis
    ports:
      - "6380:6379"
    command: --loglevel warning
  mongo-db:
    image: mongo
    env_file:
      - ./backend/.env.development
    container_name: go-mongo
    ports:
      - "27017:27017"
  mongo-express:
    image: mongo-express
    ports:
      - "8082:8081"
    env_file:
      - ./backend/.env.development
    depends_on:
      - mongo-db
volumes:
  pgdata:
