global:
  scrape_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["metrics:9090"]
  - job_name: 'dukkan'
    scrape_interval: 10s
    static_configs:
      - targets: ["go-api:8000"]
          
          
  